### ISSUE TITLE
Should `data_pointer` be wrapped around the length of `data_tape`?

### ISSUE THREAD

**Issue by Princic-1837592** [chitramdasgupta/brainf-interpreter#3]
I found out that using `wrapping_add` and `wrapping_sub` is not totally safe here because subtracting below 0 is not actually goind to `data_tape - 1` but to `18446744073709551615`, which is the max value for usize (and definitely out of range for `data_tape`). Is it ok to leave it like this?

**Comment by chitramdasgupta** [comment]
Good catch!

Fixed it with commit fe97f354d2c639a0913ea8c4be741e67730e2304

**Comment by Princic-1837592** [comment]
Actually no because subtracting unckecked will still panick and also is useless to check if the `data_pointer` is in range if yuo ensure it is by using the module

**Comment by chitramdasgupta** [comment]
I think it would be best to let this panic happen. Underflowing the data tape is the caused by the source program and the interpreter should indicate that
